version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - /home/ubuntu/GitHub/jenkins_data:/var/jenkins_home
      - /home/ubuntu/GitHub/home:/home
      - /var/run/docker.sock:/var/run/docker.sock
